# Uncomment to enable encoder
# CONFIG_EC11=y
# CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Uncomment the following line to enable the Lily58 OLED Display
CONFIG_ZMK_DISPLAY=y

#### DISPLAY 
#CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y
# External power setting for widget with bongo cat
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y
# Dedicated thread
CONFIG_ZMK_DISPLAY_DEDICATED_THREAD_STACK_SIZE=2048

#### for the bongo
CONFIG_ZMK_WIDGET_OUTPUT_STATUS=n
CONFIG_ZMK_WIDGET_LAYER_STATUS=n

#### WIDGET 
#CONFIG_ZMK_WIDGET_LAYER_STATUS=n
#CONFIG_ZMK_WIDGET_PERIPHERAL_STATUS=n
CONFIG_ZMK_WIDGET_BATTERY_STATUS=n
#CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y
CONFIG_ZMK_WIDGET_WPM_STATUS=n

#### bongo cat
CONFIG_NICE_OLED_WIDGET_WPM=y
#CONFIG_NICE_OLED_GEM_ANIMATION=y

### Turn on deep sleep
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1200000
CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=y
CONFIG_ZMK_IDLE_TIMEOUT=600000

# Enable the Nice!Oled specific widgets
#CONFIG_NICE_OLED_WIDGET_WPM=y
#CONFIG_NICE_OLED_WIDGET_BATTERY=y

### HID para nice!view ePapwerDisplay
# Enable eager deounciung
# "Eager Debouncing"
# Trying to lower the input lag.
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5

### DEBUG OPTIONS
CONFIG_ZMK_USB_LOGGING=y
CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=8000

